export default [{
    name: 'getAccountKey',
    method: 'GET',
    desc: '获取账户key',
    path: '/robot/accountKey',
    mockPath: '/robot/accountKey',
    params: {},
    options: {}
}, {
    name: 'addAccountKey',
    method: 'POST',
    desc: '获取账户key',
    path: '/robot/accountKey',
    mockPath: '/robot/accountKey',
    params: {},
    options: {}
}, {
    name: 'deleteAccountKey',
    method: 'DELETE',
    desc: '删除账户key',
    path: '/robot/accountKey/:id',
    mockPath: '/robot/accountKey/:id',
    params: {},
    options: {}
}, {
    name: 'getSelfTradeConfig',
    method: 'GET',
    desc: '获取自成交配置',
    path: '/robot/selfTradeConfig',
    mockPath: '/robot/selfTradeConfig',
    params: {},
    options: {}
}, {
    name: 'addSelfTradeConfig',
    method: 'POST',
    desc: '获取自成交配置',
    path: '/robot/selfTradeConfig',
    mockPath: '/robot/selfTradeConfig',
    params: {},
    options: {}
}]